### PR TITLE
Add debug server assembly code for i686-pc-windows-gnu

### PR DESCRIPTION
**Pull request by SpaceManiac**
- Add i686-pc-windows-gnu assembly file provided by Willox
- Give assembly files descriptive names, add comments
- Update Linux suspended_procs_buffer signature

### CODE REVIEW

**Comment by willox** [comment]
Did you get exceptions working with mingw? I haven't looked into it yet but we could replace the use of C++ exceptions with some platform specific code if necessary

**Comment by willox** [comment]
I've managed to get it working by replacing our try/catch usage with setjmp/longjmp. It's not a good approach but it seems like it'll be enough for unsupported MinGW builds to work.

I'll push it to this PR later after adding conditional compilation to it.

**Comment by willox** [comment]
LMK if that works out (or just revert it if you didn't need it)

**Comment by SpaceManiac** [comment]
It works

**Pull request merged**
