### PR TITLE
BYOND 515.1632 compat (incl. breakpoints!)

### PR DESCRIPTION
**Pull request by Absolucy**
Credit to @Dimach for most of this; I just optimized the union stuff a bit and am going to push a release

## Proof(?)

2024-03-10 (1710054488) ~ Code
2024-03-10 (1710054478) ~ Code
2024-03-10 (1710054464) ~ Code

### CODE REVIEW

**Comment by Absolucy** [comment]
go go gadget self-merge

**Comment by Absolucy** [comment]
ignore my brainfart, it works with 1633, not just 1632

**Comment by willox** [comment]
What's the `#[inline(never)]` for?

**Comment by Absolucy** [comment]
prolly not needed, but the idea was just like, it should just be a check and then an immediate jump to the correct version on the func. prolly me just overthinking things, tho.

**Comment by willox** [comment]
i feel like marking a single field access as non-inline is the most against-the-grain premature optimization i've ever seen but i'm not gonna change it

**Pull request merged**
