### PR TITLE
Update Linux signatures for BYOND 514.1588

### PR DESCRIPTION
**Pull request by Mothblocks**
Untested. Unit tests that setup a DM server would be cool.

### CODE REVIEW

**Comment by willox** [comment]
It'd be nice if this didn't remove the other signatures so that backwards compat can be kept

**Comment by Mothblocks** [comment]
It is kept:

```
 xxd -p 514.1560_byond_linux/byond/bin/libbyond.so | tr -d '\n' | rg -io 'e8........890424e8........8b008d4d..890c24'
e8ca000000890424e8424cfcff8b008d4dd4890c24

 xxd -p 514.1588_byond_linux/byond/bin/libbyond.so | tr -d '\n' | rg -io 'e8........890424e8........8b008d4d..890c24'
e8ca000000890424e88246fcff8b008d4dd4890c24
```

(Though now that I look at it I'm weirded out that the output seems to be the same?)

**Comment by Mothblocks** [comment]
Okay this probably works but there's another one I have to fix now:

> ## WARNING: Error initializing SSlua: FAILED (Couldn't find set_variable)

**Comment by willox** [comment]
Well if you'd rather test that signature finds a match against every linux release of byond since the first we supported that'd be fine too 😆

**Comment by Mothblocks** [comment]
Fair enough

**Comment by Mothblocks** [comment]
I'm gonna put a bunch of signatures in here until Auxlua works on latest Linux if you don't mind

**Comment by Mothblocks** [comment]
It works

**Comment by Mothblocks** [comment]
I didn't get a notification for the failure and also I'm pretty sure cargo check worked fine on my Windows? Wonder if old Rust is being used or something. Will take a look and see if I'm just crazy

**Comment by Mothblocks** [comment]
@willox

**Pull request merged**
