### PR TITLE
make some static muts thread locals

### PR DESCRIPTION
**Pull request by jupyterkat**
- makes static muts thread locals
- functions that call byond stuff now panic when called outside execution context
- expunge some unsafe code for safer versions
- interned strings made more sane
- swap out mpsc for flume
- changes some more hashmaps to use faster versions of hashes
- cargo update, cargo fmt ran
- sped up the debug server by alot

### CODE REVIEW

**Comment by willox** [comment]
are you saying the polling on mpsc for every instruction was a bigger bottleneck than the new thread locals?

**Comment by jupyterkat** [comment]
It’s probably the mutex existing for absolutely no reasons at all

**Comment by willox** [comment]
I guess the thread locals in auxtools are ok, could we swap back the debug server ones though? At least the one that is accessed for every single instruction

**Comment by jupyterkat** [comment]
Is there a specific reason why?

**Comment by willox** [comment]
The instruction hook function currently almost doubles init time on tg (or something like that). It's easily a case where we should be keeping it as optimized as possible.

Thread locals don't just add an init check, they're effectively adding extra layers of indirection.

**Comment by willox** [comment]
If anything I want to increase the simplicity (post-compile) of our global accesses rather than turning them in to TLS or any other kind of variable with indirection

**Pull request closed without merging**
